---

- name: "configuration play."
  hosts: web

  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 30 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for:
          timeout: 30

    # Install python if needed
    # - name: "install python for Ansible."
    #   # Your code here
    #   become: yes
    #   apt:
    #       name: python
    #       state: latest
  roles:
    # Your code here
    - configure-server-dependencies
    - configure-prometheus-node-exporter
